name: Build

on:
  push:
    paths-ignore:
      - 'dist/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
       # persist-credentials: false
        fetch-depth: 0
    - name: install
      run: npm install
    - name: build
      #run: npx @vercel/ncc build ./src/index.js  
      run: npm run build
    - name: push
      run: |

    - uses: tool3/ncc@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src: 'src/index.js'
        branch: 'main'
        commit_msg: 'Build ./dist/index.js via Github Actions'
#    - uses: actions/upload-artifact@v1
#      with:
#        name: dist
#        path: dist/